[project]
org-name= "riyafa"
version= "0.1.0"

[dependencies]


[platform]
target = "java8"

  [[platform.libraries]]
  module = "telegram"
  path = "../../../target/telegram-1.0-SNAPSHOT.jar"
  artafactId = "telegram"
  version = "0.1.0"
  groupId = "org.riyafa"

